AzureBlobStorageOperation/Controllers/FaceDetectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Threading.Tasks;
using AzureBlobStorageOperation.Models;

namespace AzureBlobStorageOperation.Controllers
{
    public class FaceDetectionController : Controller
    {
        private const string directory = "../UploadedFiles";
        private static string UplImageName = string.Empty;
        // GET: FaceDetection
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public ActionResult RenderMenu()
        {
            return PartialView("_MenuBar");
        }
        [HttpPost]
        public JsonResult SaveCandidateFiles()
        {
           string message = string.Empty, fileName = string.Empty; bool flag = false;
            //Requested File Collection
            HttpFileCollection fileRequested = System.Web.HttpContext.Current.Request.Files;
            if (fileRequested != null)
            {
                //Create New Folder
                CreateDirectory();

                //Clear Existing File in Folder
                ClearDirectory();

                for (int i = 0; i < fileRequested.Count; i++)
                {
                    var file = Request.Files[i];
                   // var actualFileName = file.FileName;
                    fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                   // int size = file.ContentLength;

                    try
                    {
                        file.SaveAs(Path.Combine(Server.MapPath(directory), fileName));
                        message = "File uploaded successfully";
                        UplImageName = fileName;
                        flag = true;
                    }
                    catch (Exception)
                    {
                        message = "File upload failed! Please try again";
                    }
                }
            }
            return new JsonResult
            {
                Data = new
                {
                    Message = message,
                    UplImageName = fileName,
                    Status = flag
                }
            };
        }

        [HttpGet]
        public async Task<dynamic> GetDetectedFaces()
        {

            var DetectedResultsInText = string.Format("Detecting...");
            var FullImgPath = Server.MapPath(directory) + '/' + UplImageName as string;
            var QueryFaceImageUrl = directory + '/' + UplImageName;


            if (UplImageName != "")
            {
                //Create New Folder
                CreateDirectory();
                DetectedResultsInText = await ComputerService.AnalyzeImageLocal(FullImgPath);

            }
            return new JsonResult
            {
                Data = new
                {
                    QueryFaceImage = QueryFaceImageUrl,
                    //MaxImageSize = MaxImageSize,
                    //FaceInfo = DetectedFaces,
                    //FaceRectangles = ResultCollection,
                    DetectedResults = DetectedResultsInText
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public void CreateDirectory()
        {
            bool exists = System.IO.Directory.Exists(Server.MapPath(directory));
            if (!exists)
            {
                try
                {
                    Directory.CreateDirectory(Server.MapPath(directory));
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }
            }
        }

        public void ClearDirectory()
        {
            DirectoryInfo dir = new DirectoryInfo(Path.Combine(Server.MapPath(directory)));
            var files = dir.GetFiles();
            if (files.Length > 0)
            {
                try
                {
                    foreach (FileInfo fi in dir.GetFiles())
                    {
                        GC.Collect();
                        GC.WaitForPendingFinalizers();
                        fi.Delete();
                    }
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }
            }
        }
    }
}

AzureBlobStorageOperation/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace AzureBlobStorageOperation
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase uploadFile)
        {
            foreach (string file in Request.Files)
            {
                uploadFile = Request.Files[file];
            }
            // Container Name - picture
            BlobManager BlobManagerObj = new BlobManager("picture");
            string FileAbsoluteUri = BlobManagerObj.UploadFile(uploadFile);

            return View();
        }

        public ActionResult Get()
        {
            // Container Name - picture
            BlobManager BlobManagerObj = new BlobManager("picture");
            List<string> fileList = BlobManagerObj.BlobList();

            return View(fileList);
        }

        public ActionResult Delete(string uri)
        {
            // Container Name - picture
            BlobManager BlobManagerObj = new BlobManager("picture");
            BlobManagerObj.DeleteBlob(uri);

            return RedirectToAction("Get");
        }
    }
}

AzureBlobStorageOperation/Views/Home/Get.cshtml
@*@model List<string>
    @{
        Layout = null;
    }

    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Get</title>
    </head>
    <body>
        <div>
            <a href="@Url.Action("Index", "Home")" style="color:green; font-size:14pt;">Add New File</a>
        </div>
        <div>
            <table border="1">
                <thead>
                    <tr>
                        <th>Picture</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (string SingleObj in Model)
                    {
                        <tr>
                            <td>
                                <img src="@SingleObj" alt="@SingleObj"
                                     style="height:100px; width: auto;" />
                            </td>
                            <td>
                                <span>@Html.ActionLink("Delete Picture", "Delete", "Home", new { uri = SingleObj }, new { })</span>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </body>
    </html>*@

@model List<string>
@{
    Layout = null;
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Events Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    @* <script src="~/Scripts/modernizr-2.6.2.js"></script>*@
</head>
<style>
    .navbar {
        background-color: teal;
        border-color: #E7E7E7;
    }

    .navbar-default .navbar-nav > li > a {
        color: #777777;
    }

    .navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:hover, .navbar-default .navbar-nav > .active > a:focus {
        background-color: #E7E7E7;
        color: #555555;
    }
</style>
<body>

    <header class="w3-display-container w3-content w3-center" style="max-width:1500px">
        <img class="w3-image" src="~/Content/photographer.jpg" alt="Me" width="1500" height="600">
        <div class="w3-display-middle w3-padding-large w3-border w3-wide w3-text-light-grey w3-center">
            <h1 class="w3-hide-medium w3-hide-small w3-xxxlarge">Upload Your Photos</h1>
            <h5 class="w3-hide-large" style="white-space:nowrap">Upload Your Photos</h5>
            <h3 class="w3-hide-medium w3-hide-small">Image Detection Application</h3>
        </div>

        <!-- Navbar (placed at the bottom of the header image) -->
        <div class="w3-bar w3-light-grey w3-round w3-display-bottommiddle w3-hide-small" style="bottom:-16px">
            <a href="@Url.Action("Index","FaceDetection")" class="w3-bar-item w3-button">Image Detection</a>
            <a href="@Url.Action("Index","Home")" class="w3-bar-item w3-button">Upload Image</a>
            <a href="@Url.Action("Get","Home")" class="w3-bar-item w3-button">Blob Storage Images</a>

        </div>
    </header>
    @*<div height="900"></div>*@
    <div style="margin-top: 20px" class="container body-content">
        <table border="1" align="center">
            <thead>
                <tr>
                    <th>Picture</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (string SingleObj in Model)
                {
                    <tr>
                        <td>
                            <img src="@SingleObj" alt="@SingleObj"
                                 style="height:400px; width: auto;" />
                        </td>
                        <td>
                            <span>@Html.ActionLink("Delete Picture", "Delete", "Home", new { uri = SingleObj }, new { })</span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>

AzureBlobStorageOperation/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>


    <!-- Header -->
    <header class="w3-display-container w3-content w3-center" style="max-width:1500px">
        <img class="w3-image" src="~/Content/photographer.jpg" alt="Me" width="1500" height="600">
        <div class="w3-display-middle w3-padding-large w3-border w3-wide w3-text-light-grey w3-center">
            <h1 class="w3-hide-medium w3-hide-small w3-xxxlarge">Upload Your Photos Here</h1>
          
        </div>

        <!-- Navbar (placed at the bottom of the header image) -->
      
    </header>


    <div>
        <a href="@Url.Action("Get", "Home")" style="color:green; font-size:14pt;">View Data</a>
    </div>
    <div>
        @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <fieldset>
                <legend>Upload File</legend>
                <ol>
                    <li>
                        <label style="margin-right:15px;">Select file </label>
                        <input type="file" name="FilePath" value="" />
                    </li>
                </ol>
                <input type="submit" value="Submit" />
            </fieldset>
        }
    </div>
</body>
</html>